### ISSUE TITLE
Краш

### ISSUE THREAD

**Issue by TheEvilRoot** [danyadev/vk-desktop-app#7]
При запуске не из папки Applications крашится 
![2018-05-25 22 08 24](https://user-images.githubusercontent.com/16425982/40562075-31795d18-6068-11e8-9b54-cbb31df7ed5b.png)

>Uncaught Exception:
Error: EROFS: read-only file system, open '/private/var/folders/6w/b79v_r1d4k9b42z2mycxsg0r0000gn/T/AppTranslocation/57360AC4-8D13-4D08-B397-3459F4653723/d/macos.app/Contents/Resources/app/renderer/users.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.writeFileSync (fs.js:1303:33)
    at Object.<anonymous> (/private/var/folders/6w/b79v_r1d4k9b42z2mycxsg0r0000gn/T/AppTranslocation/57360AC4-8D13-4D08-B397-3459F4653723/d/macos.app/Contents/Resources/app/index.js:34:6)
    at Object.<anonymous> (/private/var/folders/6w/b79v_r1d4k9b42z2mycxsg0r0000gn/T/AppTranslocation/57360AC4-8D13-4D08-B397-3459F4653723/d/macos.app/Contents/Resources/app/index.js:65:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)

> Система: macOS 10.12.6

**Comment by danyadev** [comment]
фикс #12
